POINTS_PER_POST = 0.5
POINTS_PER_LIKE = 0.1
POINTS_PER_COMMENT = 0.1
POINTS_PER_REFERRAL = 10  
POINTS_FOR_TIPPING = 20   

POINTS_FOR_REGISTRATION = 10
POINTS_FOR_VERIFICATION = 10


POST_LIMIT_DAY= 2  

MAX_MONTHLY_POST_POINTS = 30
MAX_MONTHLY_LIKE_POINTS = 15
MAX_MONTHLY_COMMENT_POINTS = 15
MAX_MONTHLY_REFERRAL_POINTS = 10 
MAX_MONTHLY_TIPPING_POINTS = 20


POINTS_FOR_WEEKLY_LEADER = 3
POINTS_FOR_MONTHLY_LEADER = 3


# This is the sum of all *regular monthly activities*.
# It's the "perfect score" we will use to scale to 100.
# One-time points and leaderboard bonuses are treated as "extra credit" on top.
TOTAL_POSSIBLE_MONTHLY_POINTS = (
    MAX_MONTHLY_POST_POINTS +
    MAX_MONTHLY_LIKE_POINTS +
    MAX_MONTHLY_COMMENT_POINTS +
    MAX_MONTHLY_REFERRAL_POINTS +
    MAX_MONTHLY_TIPPING_POINTS
)
# TOTAL = 30 + 15 + 15 + 10 + 20 = 90