POINTS_PER_POST = 0.5
POINTS_PER_LIKE = 0.1
POINTS_PER_COMMENT = 0.1
POINTS_PER_REFERRAL = 10  
POINTS_FOR_TIPPING = 20   

POINTS_FOR_REGISTRATION = 10
POINTS_FOR_VERIFICATION = 10
POST_LIMIT_DAY = 2
LIKE_LIMIT_DAY = 5
COMMENT_LIMIT_DAY = 5

POST_LIMIT_DAY= 2  

MAX_MONTHLY_POST_POINTS = 30
MAX_MONTHLY_LIKE_POINTS = 15
MAX_MONTHLY_COMMENT_POINTS = 15
MAX_MONTHLY_REFERRAL_POINTS = 10 
MAX_MONTHLY_TIPPING_POINTS = 20


POINTS_FOR_WEEKLY_LEADER = 3
POINTS_FOR_MONTHLY_LEADER = 3

TOTAL_POSSIBLE_MONTHLY_POINTS = (
    MAX_MONTHLY_POST_POINTS +
    MAX_MONTHLY_LIKE_POINTS +
    MAX_MONTHLY_COMMENT_POINTS +
    MAX_MONTHLY_REFERRAL_POINTS +
    MAX_MONTHLY_TIPPING_POINTS
)
